"""Agregar tabla user_state_history

Revision ID: 0db265d8f8fa
Revises: 
Create Date: 2024-12-01 20:29:46.983783

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0db265d8f8fa'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('results', schema=None) as batch_op:
        batch_op.drop_column('estado')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('results', schema=None) as batch_op:
        batch_op.add_column(sa.Column('estado', sa.VARCHAR(length=10), nullable=True))

    # ### end Alembic commands ###
